spring:
  mail:
    host: smtp.qiye.aliyun.com
    username:
    password:
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, file:${upload.dir}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/filecloudplus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username:
    password:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB
  mvc:
    async:
      request-timeout: 60000
mybatis-plus:
  type-enums-package: cn.mintimate.filecloud.dao
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      id-type: assign_id
  mapper-locations: classpath:/mapper/*.xml
upload.dir: file
server:
  servlet:
    session:
      timeout: 90m
  tomcat:
    accept-count: 500
    threads:
      max: 400
    connection-timeout: 60000
  port: 8081